@startuml
!include includes/C4_Container.puml

Person(QuestionSubmitter, "提问者", "提出问题的用户")
Person(AnswerProvider, "回答者", "回答问题的用户")
Person(Admin, "管理员", "管理圈子、问题和回答")

System_Boundary(didaqa, "嘀嗒问答社区") {
    Container(DidaWeb, "Dida Web App", "Vue", "嘀嗒社区的前端应用：用户在这里提问或回答")
    Container(DidaAdminWeb, "Dida Admin Web App", "Vue", "嘀嗒社区的前端应用：用户在这里提问或回答")

    Container(DidaApi, "Dida API", "Spring MVC", "嘀嗒社区API：包括用户、问答、圈子")
    ContainerDb(DidaDb, "Dida DB", "MySql", "嘀嗒社区数据库：包括用户、问答、圈子")
}

Rel(QuestionSubmitter, DidaWeb, "访问", "浏览器")
Rel(AnswerProvider, DidaWeb, "访问", "浏览器")
Rel(Admin, DidaAdminWeb, "访问", "浏览器")

Rel(DidaWeb, DidaApi, "请求", "REST")
Rel(DidaAdminWeb, DidaApi, "请求", "REST")

Rel(DidaApi, DidaDb, "读写", "Spring JPA")

@enduml